version: '3'
services:
  clickhouse-server:
    image: clickhouse/clickhouse-server:head-alpine 
    container_name: clickhouse
    ports:
      - "18123:8123"
      - "19000:9000" 
      - "19009:9009"
    ulimits:
      nofile:
        soft: 262144
        hard: 262144
    volumes:
      - ./data:/var/lib/clickhouse
      - ./logs:/var/log/clickhouse-server
      #- ./config.xml:/etc/clickhouse-server/config.xml
      #- ./users.xml:/etc/clickhouse-server/users.xml

